export const FruitNamesInEn = {
  "persimmon": "caqui",
  "strawberry": "morango",
  "banana": "banana",
  "tomato": "tomate",
  "pear": "pera",
  "apple": "maçã",
  "orange": "laranja",
  "durian": "durião",
  "blackberry": "amora",
  "lingonberry": "oxicoco vermelho",
  "kiwi": "kiwi",
  "lychee": "lichia",
  "pineapple": "abacaxi",
  "fig": "figo",
  "gooseberry": "groselha",
  "passionfruit": "maracujá",
  "plum": "ameixa",
  "greenapple": "maçã verde",
  "raspberry": "framboesa",
  "watermelon": "melancia",
  "lemon": "limão",
  "mango": "manga",
  "blueberry": "mirtilo",
  "guava": "goiaba",
  "apricot": "damasco",
  "melon": "melão",
  "tangerine": "tangerina",
  "pitahaya": "pitaia",
  "lime": "lima",
  "pomegranate": "romã",
  "dragonfruit": "fruta do dragão",
  "grape": "uva",
  "morus": "amora (amoreira)",
  "feijoa": "feijoa",
  "avocado": "abacate",
  "kiwifruit": "kiwi",
  "cranberry": "oxicoco",
  "cherry": "cereja",
  "peach": "pêssego",
  "jackfruit": "jaca",
  "annona": "anona",
  "papaya": "mamão",
  "ceylon gooseberry": "groselha do Ceilão",
  "japanese persimmon": "caqui japonês",
  "pumpkin": "abóbora",
  "pomelo": "pomelo",
  "mangosteen": "mangostão",
  "horned melon": "melão de chifre",
  "hazelnut": "avelã"
};

export const FruitNamesInPt = {
  "caqui": "persimmon",
  "morango": "strawberry",
  "banana": "banana",
  "tomate": "tomato",
  "pera": "pear",
  "maçã": "apple",
  "laranja": "orange",
  "durião": "durian",
  "amora": "blackberry",
  "oxicoco vermelho": "lingonberry",
  "kiwi": "kiwi",
  "lichia": "lychee",
  "abacaxi": "pineapple",
  "figo": "fig",
  "groselha": "gooseberry",
  "maracujá": "passionfruit",
  "ameixa": "plum",
  "maçã verde": "greenapple",
  "framboesa": "raspberry",
  "melancia": "watermelon",
  "limão": "lemon",
  "manga": "mango",
  "mirtilo": "blueberry",
  "goiaba": "guava",
  "damasco": "apricot",
  "melão": "melon",
  "tangerina": "tangerine",
  "pitaia": "pitahaya",
  "lima": "lime",
  "romã": "pomegranate",
  "fruta do dragão": "dragonfruit",
  "uva": "grape",
  "amoreira": "morus",
  "feijoa": "feijoa",
  "abacate": "avocado",
  "oxicoco": "cranberry",
  "cereja": "cherry",
  "pêssego": "peach",
  "jaca": "jackfruit",
  "anona": "annona",
  "mamão": "papaya",
  "groselha do ceilão": "ceylon gooseberry",
  "caqui japonês": "japanese persimmon",
  "abóbora": "pumpkin",
  "pomelo": "pomelo",
  "mangostão": "mangosteen",
  "melão de chifre": "horned melon",
  "avelã": "hazelnut"
};

export const fruitFamiliesTranslations = {
  "ebenaceae": 'ebenáceas',
  "rosaceae": 'rosáceas',
  "musaceae": 'musáceas',
  "solanaceae": 'solanáceas',
  "malvaceae": 'nalváceas',
  "ericaceae": 'ericáceas',
  "actinidiaceae": 'actinidiáceas',
  "sapindaceae": 'sapindáceas',
  "bromeliaceae": 'bromeliáceas',
  "moraceae": 'moráceas',
  "grossulariaceae": 'grossulariáceas',
  "passifloraceae": 'passifloráceas',
  "rutaceae": 'rutáceas',
  "cucurbitaceae": 'cucurbitáceas',
  "anacardiaceae": 'anacardiáceas',
  "myrtaceae": 'mirtáceas',
  "cactaceae": 'cactáceas',
  "lythraceae": 'litráceas',
  "vitaceae": 'vitáceas',
  "lauraceae": 'lauráceas',
  "betulaceae": 'betuláceas',
  "clusiaceae": 'clusiáceas',
  "caricaceae": 'caricáceas',
  "annonaceae": 'annonáceas',
  "salicaceae": 'salicáceas',
};

export const fruitGenusTranslations = {
  "diospyros": "dióspiros",
  "fragaria": "fragária",
  "musa": "musa",
  "solanum": "solano",
  "pyrus": "pyrus",
  "durio": "dúrio",
  "rubus": "rúbus",
  "vaccinium": "vaccinium",
  "apteryx": "apteryx",
  "litchi": "litchi",
  "ananas": "ananás",
  "ficus": "fícus",
  "ribes": "ribes",
  "passiflora": "passiflora",
  "prunus": "prunus",
  "citrus": "citrus",
  "malus": "malus",
  "citrullus": "citrullus",
  "mangifera": "mangifera",
  "psidium": "psidium",
  "cucumis": "cucumis",
  "cactaceae": "cactáceas",
  "punica": "púnica",
  "selenicereus": "selenicereus",
  "vitis": "vitis",
  "morus": "morus",
  "sellowiana": "sellowiana",
  "persea": "persea",
  "actinidia": "actinidia",
  "artocarpus": "artocarpus",
  "corylus": "corylus",
  "garcinia": "garcinia",
  "cucurbita": "cucurbita",
  "carica": "carica",
  "annonas": "annonas",
  "dovyalis": "dovyalis"
};

export const fruitOrdersTranslations = {
  "rosales": "rosales",
  "zingiberales": "zingiberales",
  "solanales": "solanales",
  "malvales": "malvales",
  "ficales": "ficales",
  "struthioniformes": "struthioniformes",
  "sapindales": "sapindales",
  "poales": "poales",
  "saxifragales": "saxifragales",
  "malpighiales": "malpighiales",
  "cucurbitales": "cucurbitales",
  "myrtales": "myrtales",
  "fagales": "fagales",
  "cucurbitaceae": "cucurbitáceas",
  "caryophyllales": "caryophyllales",
  "vitales": "vitales",
  "myrtoideae": "myrtoideae",
  "laurales": "laurales",
  "ericales": "ericales",
  "brassicales": "brassicales"
};